# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

                      - name: Vercel Action
  # You may pin to the exact commit or the version.
  # uses: amondnet/vercel-action@16e87c0a08142b0d0d33b76aeaf20823c381b9b9
  uses: amondnet/vercel-action@v25
  with:
    # Vercel token
    vercel-token: 
    # 
    vercel-args: # optional, default is 
    # if you want to comment on pr and commit, set true, default: true
    github-comment: # optional, default is true
    # if you want to comment on pr and commit, set token
    github-token: # optional
    # if you want to create github deployment, set true, default: false
    github-deployment: # optional, default is false
    # the working directory
    working-directory: # optional
    # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
    vercel-project-id: # optional
    # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
    vercel-org-id: # optional
    # The name of the project; if absent we'll use the `vercel inspect` command to determine.
    vercel-project-name: # optional
    # vercel-cli package version
    vercel-version: # optional
    # If you are work in team scope, you should set this value to your team id.
    scope: # optional
    # zeit.co token
    zeit-token: # optional
    # 
    now-args: # optional, default is 
    # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
    now-project-id: # optional
    # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
    now-org-id: # optional
    # You can assign a domain to this deployment. Please note that this domain must have been configured in the project. You can use pull request number via `{{PR_NUMBER}}` and branch via `{{BRANCH}}`
    alias-domains: # optional, default is 
          
